version: "3"
services:
  server:
    container_name: minecraft-server
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
    volumes:
      - /srv/docker/minecraft-server:/data
