version: "3"
services:
  mc-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
    volumes:
      - /srv/docker/minecraft-server:/data
  mc-web:
    image: nginx:latest
    ports:
      - 25580:80
    volumes:
      - /srv/docker/minecraft-overviewer:/usr/share/nginx/html:ro
