version: "3"
services:
  factorio:
    container_name: factorio
    image: dtandersen/factorio
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - /srv/docker/factorio/data:/factorio
